---
layout: post
title: 'Safe Driving'
date: 2020-02-10
author: DoHerasYang
color: rgb(255,102,32)
cover: ''
tags: Notes

---

# Safe Driving - Some Notes and Reflections



### 1. Purpose and Introduction

>0.0 Purpose
>
>1.1 Exceed the Allowed Speed
>
>

#### 0.0 Background 

Sometimes the driver exceed the allowed speed and the application should alert them by collecting and analysing the data such as variation of the speed, acoustic waves, and vibration waves. The application can generate some personal information about the driver.

Some information can be generated by the <u>phone accelerometer sensors</u> which is associated with the GPS inforamtion to reduce the false positive during the accident detection.

Safe application should have the these objectives: (i) inform the concerned authorities (traffic center, medical center) about the real time accidents (location, time, and user’s details), (ii) alert users if they exceed the allowed speed while driving with an audio notice, (iii) provide users the ability to search and view the 
traffic law’s provisions and penalty values in a simple and easy way, and (iv) provide the user real-time information about the current road conditions through push notifications.

The user can know or obtain the information by text, graph and audio notice or even send accident report if the mobile application did not detect the crash.

Middleware between the mobile application and the database, it can be used for analysing the data which have been transformed from the phone or application.

*[Safe Driving: A Mobile Application for Detecting Traffic Accident]*









#### 1.1 Exceed the Allowed Speed

